### ISSUE TITLE
Please upgrade to  APCu 5.1.15

### ISSUE THREAD

**Issue by ruben-herold** [iuscommunity-pkg/php72u-pecl-apcu#1]
hi,

can you please update the package to APCu 5.1.15
See Changelog for fixes:

http://pecl.php.net/package-changelog.php?package=APCu&release=5.1.15

**Comment by liamsorsby** [comment]
This bug can be closed now 😄

**Comment by carlwgeorge** [comment]
Yes, php72u-pecl-apcu-5.1.17-1 is in the main repo now.
